CREATE TABLE price (
	pk INTEGER NOT NULL AUTO_INCREMENT,
	stockName VARCHAR(256) NOT NULL,
	timeofprice TIMESTAMP NOT NULL,
	price DECIMAL(12,2),
	PRIMARY KEY (`pk`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;